image: maven:latest

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  key: maven-build
  paths:
    - .m2/repository

stages:
  - build
  - test
  - install

build:
  stage: build
  script:
    - mvn compile

test:
  stage: test
  script:
    - mvn test

install:
  stage: install
  script:
    - mvn install
  artifacts:
    paths:
      - target/*.jar